### ISSUE TITLE
Peoples page

### ISSUE THREAD

**Issue by domoritz** [uwdb/website#12]

**Comment by BrandonHaynes** [comment]
FYI -- I modified the people page to allow specification of DBLP names, and pick these values up on the project page.

**Comment by domoritz** [comment]
A few images are missing but apart from that it looks great.

**Comment by jingjingwang** [comment]
I've put pictures there for all people.
The next thing is to let everyone review his/her picture and homepage and make changes if wanted. I'm having a hard time fighting with the GFW and may not be able to respond promptly, so please help yourself if you find something :)

**Comment by akcheung** [comment]
@BrandonHaynes Maybe the dblp link should be http instead of https?

**Comment by BrandonHaynes** [comment]
I'd hardcoded http and hidden the iframe when the request was made via https; @domoritz removed the client-side check when he moved the querystring generation to the server.  We should get his thoughts on this before making any changes -- he probably had a reason!

We could also look at grabbing the DBLP entries as JSON and populating the page using client-side script.  It would look better, but might be a bit more brittle.

**Comment by akcheung** [comment]
I see. For some reason I got a "server refused connection" error when I 
try to render that page but let's check with @domoritz.

**Comment by BrandonHaynes** [comment]
Request the project page via HTTP (http://uwdb.github.io/website/projects.html) and you'll see it as it was intended.  If you load the page via HTTPS we can't create an iframe with an HTTP URI, and since dblp.uni-trier.de doesn't support HTTPS we're out of luck.  

Our options under a HTTPS request are really to hide the iframe, or display the big gray box of doom.

**Comment by akcheung** [comment]
I see. That makes sense. Thanks!

**Comment by domoritz** [comment]
> I'd hardcoded http and hidden the iframe when the request was made via https; @domoritz removed the client-side check when he moved the querystring generation to the server. We should get his thoughts on this before making any changes -- he probably had a reason!

Your idea with the iframe was really cool. I just moved the logic to the server so that we only compile the query string once and don't need to make an ajax call. 
Indeed, https doesn't work but I didn't think it was a problem because our website will be http anyway. 

We can also use some js like you did to hide the iframe but as I said, the final page will definitely not be https.

**Comment by domoritz** [comment]
> We could also look at grabbing the DBLP entries as JSON and populating the page using client-side script. It would look better, but might be a bit more brittle.

Not sure what you mean?

**Comment by BrandonHaynes** [comment]
If we CNAME to github I'm not sure we can serve HTTPS without a certificate mismatch, so this may be mostly moot.

Regarding my JSON comment -- we could perform an ajax request to http://dblp.uni-trier.de/search/publ/api?q=%3Aauthor%3AMagdalena_Balazinska%3A&format=json and parse/embed the results using client-side logic.  Since we'd have to deal with all of the field formatting, it's probably not worth pursuing.

**Comment by domoritz** [comment]
I see what you mean. It's probably not too hard if we only include the
title, authors, a link and part of the abstract. But tbh, the new dblp
website looks fine and supports infinite scrolling and all that stuff. I
changed to the new version because it doesn't grab the focus and scrolls
the page down to the iframe.
